name: Tests

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-tests.txt
        pip install -r requirements/requirements-core.txt
        pip install .
    
    - name: Run tests
      run: |
        pytest --cov-report term --cov=s2scat --cov-config=.coveragerc 
        codecov --token 99e22b3a-3f1d-40da-96af-22d2e98c31d6